[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "slurm-requests"
dynamic = ["version"]
description = 'Lightweight asynchronous SLURM REST requests with proxy support.'
readme = "README.md"
requires-python = ">=3.10"
license = "CC-BY-SA-4.0"
keywords = [
  "slurm",
  "rest",
]
authors = [
  { name = "Kwasniok", email = "Kwasniok@users.noreply.github.com" },
]
maintainers = [
  { name = "Kwasniok", email = "Kwasniok@users.noreply.github.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.10",
]
dependencies = [
  "rest-requests>=1.0.0",
]

[project.urls]
Documentation = "https://github.com/Kwasniok/pypi-slurm-requests#readme"
Issues = "https://github.com/Kwasniok/pypi-slurm-requests/issues"
Source = "https://github.com/Kwasniok/pypi-slurm-requests"

[tool.hatch.version]
path = "src/slurm_requests/__about__.py"

[tool.hatch.envs.hatch-test]
dependencies = [
  "pytest>=8.4",
  "pytest-asyncio>=1.2",
  "asyncio>=4.0.0",
]

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.14", "3.13", "3.12", "3.11", "3.10"]